# This is basic workflow to help you get started with Actions

name: Basic CI

#Control when the workflow will run

on:
  #Trigger the workflow on push or pull request events for main
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allow you to run this workflow manually from Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  #This job check out code from repo
  build:
    # The typ of runner that the job will run on
    runs-on: ubuntu-latest.

    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4  

      #Runs a single command using the runner shell
      - name: Run a one-line script
        run: echo Hello, world!

      #Runs a set of commands using the runners shell
      - name: Run a multiple-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
